### ISSUE TITLE
Which script was used for Fig.2 in The SpliZ generalizes ‘percent spliced in’ to reveal regulated splicing at single-cell resolution

### ISSUE THREAD

**Issue by tjhwangxiong** [salzmanlab/SpliZ#11]
Dear [juliaolivieri](https://github.com/juliaolivieri) , Could you please tell us which script did you use for Fig.2, as lots of scripts were provided in the directory of [SpliZ_pipeline](https://github.com/juliaolivieri/SpliZ_pipeline)[](https://user-images.githubusercontent.com/94770704/161369176-f05a0f18-c6c0-456d-ab59-dd3d747cd9cc.png)/scripts/
![image](https://user-images.githubusercontent.com/94770704/161426763-33bfc5eb-6dc5-4fec-b4a9-b992b6eec62d.png)

Thanks a lot.

**Comment by tjhwangxiong** [comment]
ggsashimi?
 https://github.com/guigolab/ggsashimi

**Comment by roozbehdn** [comment]
We used a custom in-house script to generate the sashimi/dot plots and unfortunately it is not straightforward to adapt it for general datasets. Our recommendation is to use ggsashimi on your bam files as it would be much simpler.
