### ISSUE TITLE
Error executing process > 'NFCORE_SPLIZ:SPLIZ_PIPELINE:PREPROCESS:CONVERT_BAM:PROCESS_CLASS_INPUT (1)

### ISSUE THREAD

**Issue by gabee-chan** [salzmanlab/SpliZ#12]
## Description of the bug

I'm trying to run SpliZ using bam files output from STARsolo. Everything goes well until NFCORE_SPLIZ:SPLIZ_PIPELINE:PREPROCESS:CONVERT_BAM:PROCESS_CLASS_INPUT. Specifically on the process_CI.py script.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
```
nextflow -bg run /home/gabrod/bin/SpliZ/main.nf  -c /home/gabrod/bin/SpliZ/nextflow.config --dataname Human
Colon --outdir /share/ScratchGeneral/gabrod/forSpliZ/HumanColon -profile wolfpack,conda --run_analysis true --SICILI
AN false --pin_S 0.1 --pin_z 0 --bounds 5 --light false --svd_type normdonor --n_perms 100 --grouping_level_1 Tissue
 --grouping_level_2 Stage --samplesheet /share/ScratchGeneral/gabrod/forSpliZ/Human_colon.csv --annotator_pickle /sh
are/ScratchGeneral/gabrod/GTF/hg38_ensembl.pkl --exon_pickle /share/ScratchGeneral/gabrod/GTF/hg38_ensembl_exon_boun
ds.pkl --splice_pickle /share/ScratchGeneral/gabrod/GTF/hg38_ensembl_splices.pkl --gtf /share/ScratchGeneral/gabrod/
GTF/hg38.ensGene.gtf --libraryType 10X --meta /share/ScratchGeneral/gabrod/forSpliZ/Metadata.txt --outdir /share/Scr
atchGeneral/gabrod/forSpliZ/HumanColon 
```
2. See error: 

```
Command error:
  Traceback (most recent call last):
    File "/share/ScratchGeneral/gabrod/forSpliZ/conda/nf-core-spliz-1.0dev-39088092ea5be9e9ec0058b86103f2cc/lib/pyth
on3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
      return self._engine.get_loc(casted_key)
    File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
    File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
    File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
  KeyError: 'barcode'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/gabrod/bin/SpliZ/bin/process_CI.py", line 72, in <module>
      main()
    File "/home/gabrod/bin/SpliZ/bin/process_CI.py", line 35, in main
      df["barcode_refName"] = df["barcode"].astype(str) + df["refName_ABR1"]
    File "/share/ScratchGeneral/gabrod/forSpliZ/conda/nf-core-spliz-1.0dev-39088092ea5be9e9ec0058b86103f2cc/lib/pyth
on3.9/site-packages/pandas/core/frame.py", line 3455, in __getitem__
      indexer = self.columns.get_loc(key)
    File "/share/ScratchGeneral/gabrod/forSpliZ/conda/nf-core-spliz-1.0dev-39088092ea5be9e9ec0058b86103f2cc/lib/pyth
on3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
      raise KeyError(key) from err
  KeyError: 'barcode'
```

## Expected behaviour

To get SpliZ output 

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag:

**Comment by juliaolivieri** [comment]
Hi @gabee-chan, currently we only support running from cellranger BAMs or the output of the SICILIAN pipeline (https://github.com/salzmanlab/nf-sicilian). Thanks for letting us know that you're interested in running from STARsolo output, we'll put that on our to-do list but can't promise when it will be ready

**Comment by tjhwangxiong** [comment]
> Hi @gabee-chan, currently we only support running from cellranger BAMs or the output of the SICILIAN pipeline (https://github.com/salzmanlab/nf-sicilian). Thanks for letting us know that you're interested in running from STARsolo output, we'll put that on our to-do list but can't promise when it will be ready

Dear [juliaolivieri](https://github.com/juliaolivieri), I ran SpliZ using pbmc3k.bam from cellranger. This bam contained 180440 cell barcodes (CB:Z tag). I used cell barcodes and cell type annotation from annotated pbmc3k from SeuratData package to generate meta.tsv, which had 2700 cell barcodes. Finally, I got no splice site result in summary file.

I only interested in the finally annotated cells. I hope to know whether the cell_id in  meta.tsv should include all cell barcodes in the input Bam file. Thanks a lot.

**Comment by juliaolivieri** [comment]
I think the issue might be the format of the cell ids in your `meta.tsv` file. The `cell_id` column in the `meta.tsv` file should have values of the form: `<dataname>_<cell barcode>`. For example, if the `--dataname` parameter you ran with was `chr1_sample`, then the cell ids should look like this:

```
chr1_sample_TTGCCGGTGATCCCTC
chr1_sample_CGGTATAGGTATTAGC
chr1_sample_CGTTGAGTAATTGCGT
...
```

**Comment by tjhwangxiong** [comment]
> I think the issue might be the format of the cell ids in your `meta.tsv` file. The `cell_id` column in the `meta.tsv` file should have values of the form: `<dataname>_<cell barcode>`. For example, if the `--dataname` parameter you ran with was `chr1_sample`, then the cell ids should look like this:
> 
> ```
> chr1_sample_TTGCCGGTGATCCCTC
> chr1_sample_CGGTATAGGTATTAGC
> chr1_sample_CGTTGAGTAATTGCGT
> ...
> ```

Thanks a lot. cell_id was set as BAM_id_barcode, and finally it worked successfully. Thanks again for your wonderful tools.

**Comment by liuyu988** [comment]
> Hi @gabee-chan, currently we only support running from cellranger BAMs or the output of the SICILIAN pipeline (https://github.com/salzmanlab/nf-sicilian). Thanks for letting us know that you're interested in running from STARsolo output, we'll put that on our to-do list but can't promise when it will be ready

Dear [juliaolivieri](https://github.com/juliaolivieri), I install the SpliZ according to the protocol, but unfortunately i met some problems when just running the example

my code:

> nextflow run salzmanlab/spliz \
>     -r main \
>     -latest \
>     -profile small_test_data

my error:
> executor >  local (1)
> [aa/0dc239] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:SPLIZ:CALC_SPLIZVD (test)  [100%] 1 of 1, failed: 1 ✘
> [-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:PVAL_PERMUTATIONS -
> [-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:FIND_SPLIZ_SITES  -
> [-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:SUMMARIZE_RESULTS -
> Execution cancelled -- Finishing pending tasks before exit
> -[nf-core/spliz] Pipeline completed with errors-
> Error executing process > 'NFCORE_SPLIZ:SPLIZ_PIPELINE:SPLIZ:CALC_SPLIZVD (test)'
> Caused by:
> Process `NFCORE_SPLIZ:SPLIZ_PIPELINE:SPLIZ:CALC_SPLIZVD (test)` terminated with an error exit status (1)

I am looking forward to your reply! thanks!
Yu Liu

**Comment by liuyu988** [comment]
> Cannot run program "sbatch" (in directory "/public2/home/rotation/LY/work/stage/67/bf818fcef6144597865498628bd91d/work/6c/11a16ac8635f3247bc9c2103529e5b"): error=2, No such file or directory

**Comment by kaitlinchaung** [comment]
Please open a new Issue for your support request, I'll be closing this Issue.

When opening a new Issue, please paste in your full command error.
