### ISSUE TITLE
Issues about running my own data

### ISSUE THREAD

**Issue by tjhwangxiong** [salzmanlab/SpliZ#13]
Thanks for the great tool. I ran SpliZ using bam downloaded from 10X Genomics (https://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc3k/pbmc3k_possorted_genome_bam.bam). I filtered this BAM with cell barcode from pbmc3k with SeuratData package according the suggested method by 10X Genomics (https://kb.10xgenomics.com/hc/en-us/articles/360022448251-Is-there-way-to-filter-the-BAM-file-produced-by-10x-pipelines-with-a-list-of-barcodes-).

Here is my **pbmc3k.config**
```
params {
  dataname = "pbmc3k"
  SICILIAN = false
  samplesheet = "/home/data/wangxiong/project/SpliZ/pbmc3k_samplesheet.csv"
  annotator_pickle = "/home/data/wangxiong/project/SpliZ/sicilian_wx/SICILIAN_human_hg38_Refs/annotator_file/hg38_refseq.pkl"
  exon_pickle = "/home/data/wangxiong/project/SpliZ/sicilian_wx/SICILIAN_human_hg38_Refs/exon_pickle_file/hg38_refseq_exon_bounds.pkl"
  splice_pickle = "/home/data/wangxiong/project/SpliZ/sicilian_wx/SICILIAN_human_hg38_Refs/splice_pickle_file/hg38_refseq_splices.pkl"
  gtf = "/home/data/wangxiong/project/SpliZ/sicilian_wx/SICILIAN_human_hg38_Refs/gtf_file/grch38_known_genes.gtf"
  meta = "/home/data/wangxiong/project/SpliZ/pbmc3k_meta.tsv"
  pin_S = 0.1
  pin_z = 0.0
  bounds = 5
  light = false      
  svd_type = "normdonor"
  n_perms = 100
  grouping_level_2 = "grouping_level_2"
  grouping_level_1 = "grouping_level_1"
  libraryType = "10X"
  run_analysis = true
}

params.outdir = "./results/${params.dataname}"
params.tracedir = "./results/${params.dataname}/pipeline_info"
params.schema_ignore_params = "input,single_end,show_hidden_params,validate_params,igenomes_ignore,tracedir,igenomes_base,help,monochrome_logs,plaintext_email,max_multiqc_email_size,email_on_fail,email,multiqc_config,publish_dir_mode,genome,genomes" 
```
Here is my **pbmc3k_samplesheet.csv**
```
pbmc3k_filtered,pbmc3k_filtered.bam
```
An my **pbmc3k_meta.tsv**
```
# head -5 pbmc3k_meta.tsv
cell_id grouping_level_1 grouping_level_2
CB:Z:AAACATACAACCAC-1 Control Memory CD4 T
CB:Z:AAACATTGAGCTAC-1 Control B
CB:Z:AAACATTGATCAGC-1 Control Memory CD4 T
CB:Z:AAACCGTGCTTCCG-1 Control CD14+ Mono
```
I ran my own data using this code:
```
nextflow run salzmanlab/spliz -r main -latest -c pbmc3k.config
```
However, the following errors occurred:
![image](https://user-images.githubusercontent.com/94770704/161750353-8177ccf8-5c79-42ea-bf5f-b06d3380eda6.png)
![image](https://user-images.githubusercontent.com/94770704/161750405-89005016-dc24-40af-9ac5-24ee2229a5f9.png)

I hav cat .command.sh
```
#!/bin/bash -euo pipefail
process_CI.py \
    --input_file collect-file.data \
    --meta pbmc3k_meta.tsv \
    --libraryType 10X \
    --outname pbmc3k.pq
```
I don't know the reason why I failed.

**Comment by tjhwangxiong** [comment]
Moreover,  I hope to know which software was able to view the output file (`--outname pbmc3k_filtered.class_input`) in step one 

```
#!/bin/bash -euo pipefail
light_class_input_subcols.py \
    --bams pbmc3k_filtered.bam \
    --libraryType 10X \
    --annotator hg38_refseq.pkl \
    --gtf grch38_known_genes.gtf \
    --outname pbmc3k_filtered.class_input
```
It seems that the cell_id in `pbmc3k_filtered.class_input` was different with `meta.tsv`

**Comment by wlei-amu** [comment]
I have the same errors.I wonder how you solved the problem?Thanks!

**Comment by tjhwangxiong** [comment]
> I have the same errors.I wonder how you solved the problem?Thanks!

Error occurred in my mets.tsv. Columns should be seperated with tab ('\t) but NOT blank.

**Comment by wlei-amu** [comment]
> > I have the same errors.I wonder how you solved the problem?Thanks!
> 
> Error occurred in my mets.tsv. Columns should be seperated with tab ('\t) but NOT blank.

Hello, do meta. CSV and Samplesheet. CSV need TAB (\t) to separate, don't READme files show ","?

**Comment by tjhwangxiong** [comment]
> > > I have the same errors.I wonder how you solved the problem?Thanks!
> > 
> > 
> > Error occurred in my mets.tsv. Columns should be seperated with tab ('\t) but NOT blank.
> 
> Hello, do meta. CSV and Samplesheet. CSV need TAB (\t) to separate, don't READme files show ","?
 Samplesheet. CSV, columns should be seperated by ','.  meta.tsv, Columns should be seperated with tab ('\t) (^I in shell). cell_id should be sample name_barcode.
Here are my study.

![image](https://user-images.githubusercontent.com/94770704/164373483-0eb86a5d-1097-445a-aa2a-3ecfb29b85fb.png)

![image](https://user-images.githubusercontent.com/94770704/164373506-e0355888-1321-4f38-814d-daa2b1134163.png)

![image](https://user-images.githubusercontent.com/94770704/164373533-9d3d2f1c-b65a-4e02-9155-46db1137b228.png)

Good luck. I also hope someone to develop some ploting tools for Spiz.

**Comment by wlei-amu** [comment]
Thank you very much！
