### ISSUE TITLE
Issue aboout calculating SpliZ

### ISSUE THREAD

**Issue by tjhwangxiong** [salzmanlab/SpliZ#14]
I have four celltype, including CD4T, CD8T, B, NK cells, and three groups, including control, early, late. If I just want to compare differential splicing between control and early within CD4T and CD8T cells. Should I include all groups and celltyes in meta.tsv?

If only barcodes of CD4T and CD8T cells in control and early groups were included in meta.tsv, the SpliZ value will be affected?

cell_id	grouping_level_2	grouping_level_1
Control_AAACATTGAGCTAC	Control	CD8 T
Control_AGTACTCTCAACCA	Control	CD8 T
Control_ATGTTCACCGTAGT	Control	CD4 T
Control_CGCTACTGAACAGA	Control	CD4 T
Early_TAGTTAGATGAACC 	Early	CD8 T
Early_ACCTATTGTGCCCT  	Early	CD8 T
Early_TAGAATTGTATCGG 	Early	CD4 T
Early_ATAGATACCATGGT	        Early	CD4 T

or like this

cell_id	grouping_level_2	grouping_level_1
Control_AAACATTGAGCTAC	Control	CD8 T
Control_AGTACTCTCAACCA	Control	CD8 T
Control_ATGTTCACCGTAGT	Control	CD4 T
Control_CGCTACTGAACAGA	Control	CD4 T
Early_TAGTTAGATGAACC 	Early	CD8 T
Early_ACCTATTGTGCCCT  	Early	CD8 T
Early_TAGAATTGTATCGG 	Early	CD4 T
Early_ATAGATACCATGGT	        Early	CD4 T
Late_TAGTTAGATGAACC  	Late	        CD8 T
Late_ACCTATTGTGCCCT  	Late	        CD8 T
Late_TAGAATTGTATCGG  	Late 	CD4 T
Late_ATAGATACCATGGT	        Late 	CD4 T
Control_AAACATTGAGCTAC	Control	NK
Control_AGTACTCTCAACCA	Control	NK
Control_ATGTTCACCGTAGT	Control	NK
Control_CGCTACTGAACAGA	Control	NK
Early_TAGTTAGATGAACC 	Early	NK
Early_ACCTATTGTGCCCT  	Early	NK
Early_TAGAATTGTATCGG 	Early	NK
Early_ATAGATACCATGGT	        Early	NK
Late_TAGTTAGATGAACC  	Late	        NK
Late_ACCTATTGTGCCCT  	Late	        NK
Late_TAGAATTGTATCGG  	Late 	NK
Late_ATAGATACCATGGT	        Late 	NK

Thanks.

**Comment by wlei-amu** [comment]
> I have four celltype, including CD4T, CD8T, B, NK cells, and three groups, including control, early, late. If I just want to compare differential splicing between control and early within CD4T and CD8T cells. Should I include all groups and celltyes in meta.tsv?
> 
> If only barcodes of CD4T and CD8T cells in control and early groups were included in meta.tsv, the SpliZ value will be affected?
> 
> cell_id grouping_level_2 grouping_level_1 Control_AAACATTGAGCTAC Control CD8 T Control_AGTACTCTCAACCA Control CD8 T Control_ATGTTCACCGTAGT Control CD4 T Control_CGCTACTGAACAGA Control CD4 T Early_TAGTTAGATGAACC Early CD8 T Early_ACCTATTGTGCCCT Early CD8 T Early_TAGAATTGTATCGG Early CD4 T Early_ATAGATACCATGGT Early CD4 T
> 
> or like this
> 
> cell_id grouping_level_2 grouping_level_1 Control_AAACATTGAGCTAC Control CD8 T Control_AGTACTCTCAACCA Control CD8 T Control_ATGTTCACCGTAGT Control CD4 T Control_CGCTACTGAACAGA Control CD4 T Early_TAGTTAGATGAACC Early CD8 T Early_ACCTATTGTGCCCT Early CD8 T Early_TAGAATTGTATCGG Early CD4 T Early_ATAGATACCATGGT Early CD4 T Late_TAGTTAGATGAACC Late CD8 T Late_ACCTATTGTGCCCT Late CD8 T Late_TAGAATTGTATCGG Late CD4 T Late_ATAGATACCATGGT Late CD4 T Control_AAACATTGAGCTAC Control NK Control_AGTACTCTCAACCA Control NK Control_ATGTTCACCGTAGT Control NK Control_CGCTACTGAACAGA Control NK Early_TAGTTAGATGAACC Early NK Early_ACCTATTGTGCCCT Early NK Early_TAGAATTGTATCGG Early NK Early_ATAGATACCATGGT Early NK Late_TAGTTAGATGAACC Late NK Late_ACCTATTGTGCCCT Late NK Late_TAGAATTGTATCGG Late NK Late_ATAGATACCATGGT Late NK
> 
> Thanks.

Hello.Can you run Sicilian tool successfully? 
 If possible, I would like to know whether you use NFcore/Sicilian or install it locally?
 Whether python=3.6.3 and R=3.6.1 need to be strictly restricted?Thank you very much!

**Comment by juliaolivieri** [comment]
@tjhwangxiong No need to subset your meta.tsv file. I would maintain it like it is in your second example

**Comment by tjhwangxiong** [comment]
> > I have four celltype, including CD4T, CD8T, B, NK cells, and three groups, including control, early, late. If I just want to compare differential splicing between control and early within CD4T and CD8T cells. Should I include all groups and celltyes in meta.tsv?
> > If only barcodes of CD4T and CD8T cells in control and early groups were included in meta.tsv, the SpliZ value will be affected?
> > cell_id grouping_level_2 grouping_level_1 Control_AAACATTGAGCTAC Control CD8 T Control_AGTACTCTCAACCA Control CD8 T Control_ATGTTCACCGTAGT Control CD4 T Control_CGCTACTGAACAGA Control CD4 T Early_TAGTTAGATGAACC Early CD8 T Early_ACCTATTGTGCCCT Early CD8 T Early_TAGAATTGTATCGG Early CD4 T Early_ATAGATACCATGGT Early CD4 T
> > or like this
> > cell_id grouping_level_2 grouping_level_1 Control_AAACATTGAGCTAC Control CD8 T Control_AGTACTCTCAACCA Control CD8 T Control_ATGTTCACCGTAGT Control CD4 T Control_CGCTACTGAACAGA Control CD4 T Early_TAGTTAGATGAACC Early CD8 T Early_ACCTATTGTGCCCT Early CD8 T Early_TAGAATTGTATCGG Early CD4 T Early_ATAGATACCATGGT Early CD4 T Late_TAGTTAGATGAACC Late CD8 T Late_ACCTATTGTGCCCT Late CD8 T Late_TAGAATTGTATCGG Late CD4 T Late_ATAGATACCATGGT Late CD4 T Control_AAACATTGAGCTAC Control NK Control_AGTACTCTCAACCA Control NK Control_ATGTTCACCGTAGT Control NK Control_CGCTACTGAACAGA Control NK Early_TAGTTAGATGAACC Early NK Early_ACCTATTGTGCCCT Early NK Early_TAGAATTGTATCGG Early NK Early_ATAGATACCATGGT Early NK Late_TAGTTAGATGAACC Late NK Late_ACCTATTGTGCCCT Late NK Late_TAGAATTGTATCGG Late NK Late_ATAGATACCATGGT Late NK
> > Thanks.
> 
> Hello.Can you run Sicilian tool successfully? If possible, I would like to know whether you use NFcore/Sicilian or install it locally? Whether python=3.6.3 and R=3.6.1 need to be strictly restricted?Thank you very much!

I used bam file as input in Non-sicililan model.

**Comment by tjhwangxiong** [comment]
> @tjhwangxiong No need to subset your meta.tsv file. I would maintain it like it is in your second example

Thanks a lot. I hope your great lab develop some visualization and ploting tools for the summary results. It will greatly help us interpret the results. Thanks

**Comment by wlei-amu** [comment]
> > > I have four celltype, including CD4T, CD8T, B, NK cells, and three groups, including control, early, late. If I just want to compare differential splicing between control and early within CD4T and CD8T cells. Should I include all groups and celltyes in meta.tsv?
> > > If only barcodes of CD4T and CD8T cells in control and early groups were included in meta.tsv, the SpliZ value will be affected?
> > > cell_id grouping_level_2 grouping_level_1 Control_AAACATTGAGCTAC Control CD8 T Control_AGTACTCTCAACCA Control CD8 T Control_ATGTTCACCGTAGT Control CD4 T Control_CGCTACTGAACAGA Control CD4 T Early_TAGTTAGATGAACC Early CD8 T Early_ACCTATTGTGCCCT Early CD8 T Early_TAGAATTGTATCGG Early CD4 T Early_ATAGATACCATGGT Early CD4 T
> > > or like this
> > > cell_id grouping_level_2 grouping_level_1 Control_AAACATTGAGCTAC Control CD8 T Control_AGTACTCTCAACCA Control CD8 T Control_ATGTTCACCGTAGT Control CD4 T Control_CGCTACTGAACAGA Control CD4 T Early_TAGTTAGATGAACC Early CD8 T Early_ACCTATTGTGCCCT Early CD8 T Early_TAGAATTGTATCGG Early CD4 T Early_ATAGATACCATGGT Early CD4 T Late_TAGTTAGATGAACC Late CD8 T Late_ACCTATTGTGCCCT Late CD8 T Late_TAGAATTGTATCGG Late CD4 T Late_ATAGATACCATGGT Late CD4 T Control_AAACATTGAGCTAC Control NK Control_AGTACTCTCAACCA Control NK Control_ATGTTCACCGTAGT Control NK Control_CGCTACTGAACAGA Control NK Early_TAGTTAGATGAACC Early NK Early_ACCTATTGTGCCCT Early NK Early_TAGAATTGTATCGG Early NK Early_ATAGATACCATGGT Early NK Late_TAGTTAGATGAACC Late NK Late_ACCTATTGTGCCCT Late NK Late_TAGAATTGTATCGG Late NK Late_ATAGATACCATGGT Late NK
> > > Thanks.
> > 
> > 
> > Hello.Can you run Sicilian tool successfully? If possible, I would like to know whether you use NFcore/Sicilian or install it locally? Whether python=3.6.3 and R=3.6.1 need to be strictly restricted?Thank you very much!
> 
> I used bam file as input in Non-sicililan model.

Thank you very much！
