### ISSUE TITLE
Divide by zero error in variance_adjusted_permutations_bytiss.py

### ISSUE THREAD

**Issue by apdavid** [salzmanlab/SpliZ#2]
I am running my own data through and it was able to process the SpliZ scores, but with the param `anaysis = true` in the config file running this with my data resulted in the following error shown below.

Also I noticed that the `free_annotation` variable was not mentioned in the config file or shows up in the output of calculated SpliZ scores and we are interested in doing differential splicing analysis, do I need to change the grouping variables to achieve this? My free annotation is in the format: (S1 ... S14)

```
  Traceback (most recent call last):
    File "/wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/bin/variance_adjusted_permutations_bytiss.py", line 196, in <module>
      main()
    File "/wynton/home/tjan/adavid/.nextflow/assets/salzmanlab/spliz/bin/variance_adjusted_permutations_bytiss.py", line 154, in main
      out_df["pval_adj"] = multipletests(out_df["pval"],alpha, method="fdr_bh")[1]
    File "/wynton/home/tjan/adavid/.conda/envs/nf_spliz_env/lib/python3.9/site-packages/statsmodels/stats/multitest.py", line 147, in multipletests
      alphacSidak = 1 - np.power((1. - alphaf), 1./ntests)
  ZeroDivisionError: float division by zero

Work dir:
  /wynton/home/tjan/adavid/work/bb/67b2a8e594213a901087bdf709e303

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```

Output of `.command.sh`:
```
#!/bin/bash -euo pipefail
variance_adjusted_permutations_bytiss.py \
    --input /wynton/home/tjan/adavid/work/8c/f4bf9521c938f448d35c84f4073dca/utricle-filtered_sym_SVD_normdonor_S_0.1_z_0.0_b_5_SICILIAN.pq \
    --num_perms 100 \
    --grouping_level_2 tissue \
    --grouping_level_1 compartment \
    --outname_all_pvals utricle-filtered_outdf_tissue-compartment_100_S_0.1_z_0.0_b_5_SICILIAN.tsv \
    --outname_perm_pvals utricle-filtered_pvals_tissue-compartment_100_S_0.1_z_0.0_b_5_SICILIAN.tsv \
    --outname_log pval_permutations.log
```

**Comment by kaitlinchaung** [comment]
Hi @apdavid,

Can you please paste in your config file, for reference?

Regarding the `free_annotation` variable, yes, you should change the `grouping_level_2` column to the metadata column that you'd like to perform differential analysis on. 

Regarding the error that you got from the pval permutations step, I've seen that error before when the `input` file does not contain annotated values for the `grouping_level_1` and `grouping_level_2` columns. For example, if `grouping_level_2=free_annotation` and your `input` file has all NAs in the `free_annotation` column, then it will have the error above. 

But it would be the most helpful to see your config file and if you could please describe what metadata columns you'd like to use to analyze. 

Thanks!

**Comment by apdavid** [comment]
Hi @kaitlinchaung,

Below is the config file for reference. I am planning to switch `grouping_level_2` to `free_annotation` and `grouping_level_1` to `compartment` or `tissue` per your suggestion. The way that I set up these metadata variables was per the **juliaolivieri/SpliZ_pipeline**:

* `free_annotation`: The most specific annotation of the cells (e.g. cell type)
     * these are named after the cluster names: *S1 [...] S14*

* `compartment`: The next most specific annotation of the cells (every value in the column can be the same)
     * all have the same value, 'utricle'

* `tissue`: The most general annotation of the cells (every value in the column can be the same)
     * all have the same value, 'utricle'

**I also triple-checked and there are no NA's in any of these metadata columns**

Here is the *.config file:
```
process {
  executor = 'local'
  memory = { 1.GB * task.attempt }
  time = { 1.h * task.attempt }
  errorStrategy = { task.exitStatus in [143,137,104,134,139] ? 'retry' : 'finish' }
  maxRetries = 3
}

params {
  dataname = "utricle-filtered"
  input_file = "utricle-pre-spliz-filtered.tsv"
  SICILIAN = true
  pin_S = 0.1
  pin_z = 0.0
  bounds = 5
  light = false
  svd_type = "normdonor"
  n_perms = 100
  grouping_level_2 = "tissue"
  grouping_level_1 = "free_annotation"
  libraryType = "SS2"
  run_analysis = true
}

params.outdir = "/wynton/group/tjan/adavid/spliz/results/${params.dataname}"
params.tracedir = "/wynton/group/tjan/adavid/spliz/results/${params.dataname}/pipeline_info"
params.schema_ignore_params = "input,single_end,show_hidden_params,validate_params,igenomes_ignore,tracedir,igenomes_base,help,monochrome_logs,plaintext_email,max_multiqc_email_size,email_on_fail,email,multiqc_config,publish_dir_mode,genome,genomes"   
```

**Comment by kaitlinchaung** [comment]
Hi @apdavid,

Thanks for the info! 

Looking at your metadata descriptions, if you only have 1 unique value for both `compartment` and `tissue`, it might be more helpful to do `grouping_level_1 = dummy` and `grouping_level_2 = free_annotation`.

Can you also please share part of your `input_file` with me somehow? What could work is either pasting in the first couple of lines, or emailing a subsample of the file(at kaitlin3@stanford.edu). 

Thanks!

**Comment by apdavid** [comment]
The following process passed:
```
[ab/92e87c] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:PVAL_PERMUTATIONS (utricle-filtered) [100%] 1 of 1 ✔
``` 
With the following parameters:
```
grouping_level_1 = "tissue" # aka `utricle`
grouping_level_2 = "free_annotation"
```

Do you still recommend switching tissue to "dummy", might that affect the downstream analyses, which are still running or should I just wait to get back to you about that?

```
[5d/efb02a] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:FIND_SPLIZ_SITES (utricle-filtered)  [  0%] 0 of 1
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:ANALYSIS:SUMMARIZE_RESULTS                    -
```

**Comment by kaitlinchaung** [comment]
@apdavid 

Glad to hear it!

Using `grouping_level_1 = tissue` and `grouping_level_1 = dummy` will effectively be the same. That is because you only have 1 value for `tissue`, so you are effectively only comparing all the `free_annotation` values against each other. However, if you use a different `grouping_level_1` that has more than 1 unique value, then that change will effect the results because you will be compartmentalizing your analysis by more than one group.

Hope that helps!

**Comment by kaitlinchaung** [comment]
Another comment about the intial error, is that it likely had to do with `grouping_level_2 = tissue`. Because there is only one unique value in that column, there was only one group to compare for each `free_annotation` value. Thus, the script errored out because it cannot compare the one group to itself.
