### ISSUE TITLE
SpliZ and SpliZVD for bulk RNA-seq

### ISSUE THREAD

**Issue by RocesV** [salzmanlab/SpliZ#22]
Dear @juliaolivieri  @roozbehdn  @kaitlinchaung  @salzmanlab-admin ,

thank you very much for developing this project. Could SpliZ and SpliZVD values be suitable for bulk RNA-seq data replacing cells by samples?

Cheers,

Roces V.

**Comment by roozbehdn** [comment]
Hi, yes you can run spliz on bulk data by setting libraryType to SS2, for SS2 each fastq file is a single cell and for bulk each fastq file would be a separate sample

**Comment by RocesV** [comment]
Thanks very much for the response @roozbehdn ! Super useful to know. Could you please give me some datails about the implementation to bulk RNA-seq data?

1) Can nextflow salzmanlab/spliz be runned straight with fastq files? How i should specify this if possible?
2) Can i use to run the nextflow salzmanlab/spliz .bam files comming from other aligner (e.g STAR alone or GSNAP)?
3) Despite it works well with the small example data, I have tried to run nextflow salzmanlab/spliz with hg19 .bam files comming from GSNAP. Any idea of how to solve this or if this is possible with this type of files? 

Detailed information:

`nextflow run salzmanlab/spliz     -r main     -latest     -c HumanBrain.config
N E X T F L O W  ~  version 21.04.0
Pulling salzmanlab/spliz ...
 Already-up-to-date
Launching `salzmanlab/spliz` [small_hugle] - revision: 594532c1b1 [main]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  salzmanlab/spliz v1.0dev
------------------------------------------------------

Core Nextflow options
  revision              : main
  runName               : small_hugle
  container             : kaitlinchaung/spliz:dev
  launchDir             : /mnt/k/2.Tools/SpliZ
  workDir               : /mnt/k/2.Tools/SpliZ/work
  projectDir            : /home/rocesv/.nextflow/assets/salzmanlab/spliz
  userName              : rocesv
  profile               : standard
  configFiles           : /home/rocesv/.nextflow/assets/salzmanlab/spliz/nextflow.config, /mnt/k/2.Tools/SpliZ/nextflow.config, /mnt/k/2.Tools/SpliZ/HumanBrain.config

Input/output options
  dataname              : HumanBrainMale
  outdir                : ./results/HumanBrainMale
  pin_S                 : 0.1
  pin_z                 : 0.0
  bounds                : 5
  light                 : false
  svd_type              : normdonor
  grouping_level_1      : tissue
  grouping_level_2      : phase
  n_perms               : 100
  annotator_pickle      : hg19.pkl
  exon_pickle           : hg19_exon_bounds.pkl
  splice_pickle         : hg19_splices.pkl
  libraryType           : SS2
  gtf                   : hg19.ensGene.gtf
  rank_quant            : 0
  samplesheet           : /mnt/k/0.TestData/Homo_sapiens/HumanBrainMale_samplesheet.csv
  meta                  : /mnt/k/0.TestData/Homo_sapiens/metadata_HumanBrainMale.tsv

Max job request options
  max_memory            : 800 GB
  max_time              : 10d

Other parameters
  max_multiqc_email_size: 25 MB

------------------------------------------------------
 Only displaying parameters that differ from defaults.
------------------------------------------------------
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:PREPROCESS:CONVERT_BAM:CLASS_INPUT_SS2  -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:PREPROCESS:CONVERT_BAM:PROCESS_CLASS... -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:PREPROCESS:CONVERT_BAM:CLASS_INPUT_SS2  -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:PREPROCESS:CONVERT_BAM:PROCESS_CLASS... -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:PREPROCESS:CONVERT_BAM:ANN_SPLICES      -
[-        ] process > NFCORE_SPLIZ:SPLIZ_PIPELINE:SPLIZ:CALC_SPLIZVD                      -
Argument of `file` function cannot be null

 -- Check script '/home/rocesv/.nextflow/assets/salzmanlab/spliz/./workflows/./../subworkflows/local/preprocess.nf' at line: 33 or see '.nextflow.log' file for more details`

CONFIG FILE:

`params {
  dataname = "HumanBrainMale"
  SICILIAN = false
  samplesheet = "/mnt/k/0.TestData/Homo_sapiens/HumanBrainMale_samplesheet.csv"
  annotator_pickle = "hg19.pkl"
  exon_pickle = "hg19_exon_bounds.pkl"
  splice_pickle = "hg19_splices.pkl"
  gtf = "hg19.ensGene.gtf"
  meta = "/mnt/k/0.TestData/Homo_sapiens/metadata_HumanBrainMale.tsv"
  pin_S = 0.1
  pin_z = 0.0
  bounds = 5
  light = false
  svd_type = "normdonor"
  n_perms = 100
  grouping_level_2 = "phase"
  grouping_level_1 = "tissue"
  libraryType = "SS2"
  run_analysis = false
}

params.outdir = "./results/${params.dataname}"
params.tracedir = "./results/${params.dataname}/pipeline_info"
params.schema_ignore_params = "input,single_end,show_hidden_params,validate_params,igenomes_ignore,tracedir,igenomes_base,help,monochrome_logs,plaintext_email,max_multiqc_email_size,email_on_fail,email,multiqc_config,publish_dir_mode,genome,genomes"`

METADATA FILE:
cell_id grouping_level_2        grouping_level_1
HumanBrainMale_1        Infant  Brain
HumanBrainMale_2        Toddler Brain
HumanBrainMale_3        School  Brain

SAMPLESHEET FILE:
HumanBrainMale_1,/mnt/k/0.TestData/Homo_sapiens/E-MTAB-6814/male/4.infant/4_5521sTS.Human.Brain.271dpb.Male.sorted.bam
HumanBrainMale_2,/mnt/k/0.TestData/Homo_sapiens/E-MTAB-6814/male/5.toddler/5_5837sTS.Human.Brain.4ypb.Male.sorted.bam
HumanBrainMale_3,/mnt/k/0.TestData/Homo_sapiens/E-MTAB-6814/male/6.schoolagechild/6_5537sTS.Human.Brain.8ypb.Male.sorted.bam
