### ISSUE TITLE
result explanation

### ISSUE THREAD

**Issue by houruiyan** [salzmanlab/SpliZ#5]
Dear Dr Chaung, I got a table about the differential SpliZ in different celltype and different conditional. But I do not know how to explain it. I want to find out the significant different splicing gene in different condition of the same celltype. And I also want to find out the significant splicing gene in the different celltype of the same condition. But it seems that this table can not give me the p value.
![image](https://user-images.githubusercontent.com/56068158/136719281-d3af75c5-a59e-47f8-8e20-c3aa44f038a6.png)

Look at this table above, I especially want to find out the differential splicing gene in the MS and Ctrl. But the scZ_pvalue is nan. Could you help me? Thank you in advance!

**Comment by juliaolivieri** [comment]
Thanks for the questions. First: Can you sort the summary file by `scZ_pval`? A value of `NaN` is expected in the results for comparisons with very little evidence of differential splicing between groups, and rows with more evidence of differential splicing should have an actual p value there.

For the question about comparing the conditions: `grouping_level_1 = experiment condition` indicates that the analysis should be performed independently for each experiment condition. So, for example, if the experiment conditions are MS and Ctrl,` grouping_level_1 = experiment condition` indicates that you want to find differences within MS or within Ctrl, but not between MS and Ctrl.

For grouping_level_2, if you set `grouping_level_2 = cell type` it means you want to find differences between cell types. So you'd be looking for differences between astrocytes and neurons, for example. 

Setting `grouping_level_1 = experiment condition` and `grouping_level_2 = cell type` means that you would find differences between MS neurons and MS astrocytes, or Ctrl neurons and Ctrl astrocytes, but not between MS neurons and Ctrl neurons.

Setting `grouping_level_1 = cell type` and `grouping_level_2 = experiment condition` means you would find differences between the same cell type in different experimental conditions (e.g. differences between MS neurons and Ctrl neurons), but not between different cell types (e.g. you wouldn't find differences between MS neurons and Ctrl astrocytes).

Feel free to ask more clarification questions about any of this.

**Comment by houruiyan** [comment]
Thank you very much! Your explanation is really clear!!

**Comment by tjhwangxiong** [comment]
> Thank you very much! Your explanation is really clear!!

Dear [houruiyan](https://github.com/houruiyan), which .config file did you change or did you generate when you ran your own data? I just ran test data sucessfully, but I did not know how to run my own data using nextflow SpliZ pipline.
