### ISSUE TITLE
Example input files for non-SICILIAN Inputs 

### ISSUE THREAD

**Issue by demar01** [salzmanlab/SpliZ#6]
Hello,

Thanks for developing this great tool! Would it be possible to provide an example of argument files required for non-SICILIAN inputs? eg Tumor_5_samplesheet.csv (samplesheet)  and metadata_tumor_5.tsv (meta)

Thanks!

**Comment by kaitlinchaung** [comment]
Hi there, 

Here is an example of what a samplesheet may look like:
```
Tumor_5_S1,home/data/tumor_5_S1_L001.bam
Tumor_5_S2,home/data/tumor_5_S2_L002.bam
Tumor_5_S3,home/data/tumor_5_S3_L003.bam
```

And here is an example of what a metadata file might look like:
```
cell    tissue  compartment
Tumor_5_S1_TATTCCTC Bladder Epithelial
Tumor_5_S1_TGGCCACA Lung    Epithelial
Tumor_5_S1_TGGCCACA Spleen  Epithelial
Tumor_5_S2_TGGCCACA Bladder Endothelial
Tumor_5_S2_TGGCCACA Lung    Endothelial
Tumor_5_S2_TGGCCACA Spleen  Endothelial
Tumor_5_S3_TGGCCACA Bladder Stromal
Tumor_5_S3_TATTCCTC Lung    Stromal
Tumor_5_S3_TGGCCACA Spleen  Stromal
```
Using this metadata, your `grouping_level_1` or `grouping_level_2` columns could be `tissue` or `compartment`.

Hope that helps!
