### ISSUE TITLE
Input files and experiment design

### ISSUE THREAD

**Issue by MEFarhadieh** [salzmanlab/SpliZ#7]
Thanks for this great tool!

SpliZ small_test_data is perfectly run in my cluster. However, there are some questions that confuse me.  I use SICILIAN for my 10X data, but I see there are some differences between my `sicilian_called_splice_juncs.tsv` output and example is used in small_data `small.tsv`. 

I know that `called` column is 1 for all junctions that should be included in the analysis, 0 otherwise, but I don't have any `called` column in my data. Also I don't how to make it.

`numReads` column in my tsv indicates total reads for a specific read, and `numReads_per_cell` indicates reads per each cell. I guess `numReads` in small.tsv equals to `numReads_per_cell` my tsv.

Should I remove other columns which are not exist in small.tsv ?

Dose `cell` column made by adding samples IDs and barcodes?

I want to use SpliZ for study differential splicing between different experimental groups in same cell type. I think I should set `grouping_level_1 = cell type` and `grouping_level_2 = experiment group`. However, I don't know should I make a tsv file includes barcodes, cell type, and experiment group? Should I merge this file with sicilian_called_splice_juncs.tsv? or set it as an input parameter?

Is it enough to just change lines 61:63 of `nextflow.config`? or I should change more lines and files for setting SpliZ base on my resources?

Can I use `scZ_median` and `scZ_pval` as cutoff parameters for downstream analysis?

For sashimi plots in Elife and Nature Methods papers, do you get data from SpliZ outputs or SICILIAN outputs?

I'm so sorry for asking too many questions.

**Comment by juliaolivieri** [comment]
Do you have a "postprocessed" file from SICILIAN? That file should have the correct columns for input into the SpliZ.
Regardless, you shouldn't need to remove columns that don't exist in `small.tsv`; only the necessary columns will be used from your input file.
Yes, the "cell" column is of the format `<sample_id>_<barcode>` (it should exist in the postprocessed SICILIAN file).
That looks like the right assignment of grouping level 1 and grouping level 2 to me. Yes, you should merge "cell type" and "experiment group" columns into your SICILIAN tsv.
Yes, those should be the only lines you need to change.
Yes, using cutoffs on `scZ_median` and `scZ_pval` for downstream analysis is correct.
We used the output of the SpliZ to decide which genes to plot, though if you already know the genes you are interested in, the SICILIAN file contains all the information you need to make the plots.

Let us know if you have any more problems!

**Comment by MEFarhadieh** [comment]
Thank you so much. I didn't know I had to run SICILIAN_post_process.py.
