### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by wlei-amu** [salzmanlab/SpliZ#8]
Hello, thank you for your great tools! I meet some trouble when I use them. Hope to get your help!
I can't download this environment file according to this link:https://raw.githubusercontent.com/salzmanlab/SpliZ/main/environment.yml
I  can't find the main folder on Git.

**Comment by juliaolivieri** [comment]
This file is available in the first level of the git directory (no need to go into any subdirectories): https://github.com/salzmanlab/SpliZ/blob/main/environment.yml

**Comment by wlei-amu** [comment]
Thanks for your reply.

**Comment by wlei-amu** [comment]
Hi.I have successfully installed the tool.But there are two questions I'd like to ask:
Firstly,Can you give me a code example to help me run the non-sicilian Inputs for this tool?
Second,How do I enter the code if I want to run the tool using Docker?
Thank you very much！

**Comment by juliaolivieri** [comment]
What inputs do you have? 10X BAM files? And we don't currently have a docker image for this pipeline, so I don't think running with docker would work.

**Comment by tjhwangxiong** [comment]
> This file is available in the first level of the git directory (no need to go into any subdirectories): https://github.com/salzmanlab/SpliZ/blob/main/environment.yml

Dear [juliaolivieri](https://github.com/juliaolivieri), May I ask which script or software did your group used for Fig 2. It looks pretty nice!
![image](https://user-images.githubusercontent.com/94770704/161188519-72848d8a-b4fc-4a81-badd-6d9d9f2f21d4.png)

Thanks a lot for SpliZ.

**Comment by wlei-amu** [comment]
> What inputs do you have? 10X BAM files? And we don't currently have a docker image for this pipeline, so I don't think running with docker would work.

I have 10X BAM files from cellranfer.But I don't know how I should modify the .config file and what code to run?Thanks

**Comment by kaitlinchaung** [comment]
Please see this section for how to format samplesheets:
https://github.com/salzmanlab/SpliZ#samplesheets

Please see this section for non-SICILIAN parameters:
https://github.com/salzmanlab/SpliZ#optional-parameters-for-non-sicilian-inputs-sicilian--false

I would recommend modifying your config file with the parameters above.

I have updated the readme to reflect the above. I'm also closing this because it's not relevant to the original issue which has been solved, please re-open a new issue if problems persist.

**Comment by tjhwangxiong** [comment]
> 

Thanks a lot for providing section 5 Run the pipeline on your own dataset.
