### ISSUE TITLE
Running small_test_data

### ISSUE THREAD

**Issue by tjhwangxiong** [salzmanlab/SpliZ#9]
`nextflow run salzmanlab/spliz \
    -r main \
    -latest \
    -profile small_test_data`

When I ran this code, the following occurred:

`N E X T F L O W  ~  version 21.04.0
Pulling salzmanlab/spliz ...
 Already-up-to-date
Launching `salzmanlab/spliz` [distracted_agnesi] - revision: 694d32b88a [main]
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config`

And an error occurred
![image](https://user-images.githubusercontent.com/94770704/161098762-3ef999aa-c2cf-41ad-b6ee-c5a55fb58056.png)

I don't know whether this happened due to my network or something else.

**Comment by juliaolivieri** [comment]
I'm not sure why the connection was refused here. You can try cloning the github repo and running locally:
```
git clone https://github.com/salzmanlab/SpliZ.git
cd SpliZ
nextflow run main.nf -profile small_test_data
```

**Comment by tjhwangxiong** [comment]
> I'm not sure why the connection was refused here. You can try cloning the github repo and running locally:
> 
> ```
> git clone https://github.com/salzmanlab/SpliZ.git
> cd SpliZ
> nextflow run main.nf -profile small_test_data
> ```

Thanks for your reply. I did git clone https://github.com/salzmanlab/SpliZ.git, and this error still occurred.
![image](https://user-images.githubusercontent.com/94770704/161174039-95b1e3ed-4360-4c01-be34-c4513e295165.png)
![image](https://user-images.githubusercontent.com/94770704/161174056-d4098fb2-4fab-4fe0-890d-e72921810954.png)

Shall I edit the nextflow.config or main.nf to change the directory of nfcore_custom.config using the local directory?

**Comment by kaitlinchaung** [comment]
Hi, I would recommend modifying your local version of the config aka the one that you just cloned.
That file should be in `./SpliZ/small_data/small.config`

I would modify the `input_file` param to be the full path of the local version of the small.pq file, which should be in:
`./SpliZ/small_data/small.pq`.

So your `small.config` should look something like this:
```
params {
  dataname = "test"
  input_file = "small_data/small.pq"
  SICILIAN = true
  pin_S = 0.1
  pin_z = 0.0
  bounds = 5
  light = false      
  svd_type = "normdonor"
  n_perms = 100
  grouping_level_2 = "compartment"
  grouping_level_1 = "tissue"
  libraryType = "10X"
  run_analysis = true
}

params.outdir = "./results/${params.dataname}"
params.tracedir = "./results/${params.dataname}/pipeline_info"
params.schema_ignore_params = "input,single_end,show_hidden_params,validate_params,igenomes_ignore,tracedir,igenomes_base,help,monochrome_logs,plaintext_email,max_multiqc_email_size,email_on_fail,email,multiqc_config,publish_dir_mode,genome,genomes" 
```

of course, you will want to modify the path to be the full path

**Comment by tjhwangxiong** [comment]
> WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config

Thanks for your help. 
This warnning still occurred.
`WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config`

Shall I modify nextflow.config?

**Comment by kaitlinchaung** [comment]
Hi, I ran the same test command and I was unable to recreate the error. 
I did find this error which seems similar to what you are receiving:
https://github.com/nf-core/rnaseq/issues/401

As for that warning message above, that is just a warning that should not be causing your run to fail. The pipeline should be able to bypass that warning.

Can you please run this command and let me know the error message that you are receiving?
```
nextflow run main.nf \
-r main \
-latest \
--input_file small_data/small.pq <<PLEASE CHANGE THIS>> \
--SICILIAN true \
--grouping_level_1 "compartment" \
--grouping_level_2 "tissue" \
--libraryType "10X" \
--run_analysis true
--max_cpus 1 
```

**Comment by tjhwangxiong** [comment]
> Hi, I ran the same test command and I was unable to recreate the error. I did find this error which seems similar to what you are receiving: [nf-core/rnaseq#401](https://github.com/nf-core/rnaseq/issues/401)
> 
> As for that warning message above, that is just a warning that should not be causing your run to fail. The pipeline should be able to bypass that warning.
> 
> Can you please run this command and let me know the error message that you are receiving?
> 
> ```
> nextflow run main.nf \
> -r main \
> -latest \
> --input_file small_data/small.pq <<PLEASE CHANGE THIS>> \
> --SICILIAN true \
> --grouping_level_1 "compartment" \
> --grouping_level_2 "tissue" \
> --libraryType "10X" \
> --run_analysis true
> --max_cpus 1 
> ```

Thanks a lot. I have modified `./SpliZ/small_data/small.config` as suggested:
```params {
  dataname = "test"
  input_file = "small_data/small.pq"
  SICILIAN = true
  pin_S = 0.1
  pin_z = 0.0
  bounds = 5
  light = false      
  svd_type = "normdonor"
  n_perms = 100
  grouping_level_2 = "compartment"
  grouping_level_1 = "tissue"
  libraryType = "10X"
  run_analysis = true
}

params.outdir = "./results/${params.dataname}"
params.tracedir = "./results/${params.dataname}/pipeline_info"
params.schema_ignore_params = "input,single_end,show_hidden_params,validate_params,igenomes_ignore,tracedir,igenomes_base,help,monochrome_logs,plaintext_email,max_multiqc_email_size,email_on_fail,email,multiqc_config,publish_dir_mode,genome,genomes" 
```

And re-ran
 ```nextflow run main.nf -profile small_test_data```
 This time it worked successfully.
![image](https://user-images.githubusercontent.com/94770704/161187461-d4d18929-8f97-43bc-8cf1-6710fbaac3ad.png)

Thanks all.

**Comment by tjhwangxiong** [comment]
Dear&nbsp;Julia Eve Olivieri


May I ask which script or software did you use for Fig.2. It looks pretty nice.









Department of Laboratory Medicine, Tongji Hospital,
Tongji Medical College, Huazhong University of Science and Technology,
Wuhan, 430030, China
Tel: +86 027-83663414
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; +86 13554663391
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Apr 1, 2022 02:20 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [salzmanlab/SpliZ] Running small_test_data (Issue #9)

&nbsp;



 
I'm not sure why the connection was refused here. You can try cloning the github repo and running locally:
 git clone https://github.com/salzmanlab/SpliZ.git cd SpliZ nextflow run main.nf -profile small_test_data
